name: Hello world
# on:
#   push:
#     branches:
#       - external-pr-merge  # Trigger the scan when merging from this branch to main

on:
  pull_request:
    branches:
      - external-pr-merge
    types:
      - opened
      - synchronize

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
